project:
  type: website
  output-dir: docs

website:
  title: "SO - Fall 2025"
  description: "Course materials for SO - Fall 2025"
  site-url: "https://os-gei-udl-2526-105012.github.io/course/"
  repo-url: https://github.com/os-gei-udl-2526-105012/course

  sidebar:
    logo: /figures/logo.png
    logo-width: 75px
    logo-height: 75px
    logo-alt: "SO Logo"
    pinned: true
    tools:
    - icon: house
      href: "index.html"
      text: "Home"
    - icon: github
      href: "https://github.com/os-gei-udl-2526-105012/course"
      text: "GitHub organization"
    - icon: person-fill
      text: "Sakai"
      href: "https://cv.udl.cat/"

    style: "docked"
    search: false
    collapse-level: 1
    contents:
      - section: Informació del curs
        contents:
          - href: ./course-information/schedule.html
            text: Planificació
      - section: Diapositives
        contents:
          - href: ./slides/01-introduction.qmd
            text: Unitat 01 · Introducció als sistemes operatius
          - href: ./slides/01-c.qmd
            text: Unitat 01 · Introducció a la programació de Sistema (I) (C)
          - href: ./slides/02-kernel.qmd
            text: Unitat 02 · Kernel de Linux
          - href: ./slides/02-syscalls.qmd
            text: Unitat 02 · Crides a sistema
          - href: ./slides/03-procs.qmd
            text: Unitat 03 · Processos
          - href: ./slides/03-create.qmd
            text: Unitat 03 · Creació de processos
          - href: ./slides/03-signals.qmd
            text: Unitat 03 · Senyals
          - href: ./slides/03-communicate.qmd
            text: Unitat 03 · Comunicació entre processos
          - href: ./slides/03-pipes.qmd
            text: Unitat 03 · Pipes
          - href: ./slides/04-sched.qmd
            text: Unitat 04 · Planificació de processos
          - href: ./slides/04-sched-part2.qmd
            text: Unitat 04 · Planificació de processos · Justícia
          - href: ./slides/04-sched-part3.qmd
            text: Unitat 04 · Planificació de processos · Linux
          

      - section: Apunts
        contents:
          - href: ./notes/01-introduction.qmd
            text: Unitat 01 ·Introducció als sistemes operatius
          - href: ./notes/03-process.qmd
            text: Unitat 03 · Gestió de processos amb C (userspace)
      - section: Laboratoris
        contents:
          - section: Unitat 01
            contents:
              - href: ./labs/01-lab-introduction.qmd
                text: Laboratori · Virtualització i Control de Versions 
              - href: ./labs/01-introduction/lab01.qmd
                text: Laboratori 1 · Instal·lació i configuració d'un entorn Linux
              - href: ./labs/01-introduction/lab02.qmd
                text: Laboratori 2 · Configurant el meu entorn de desenvolupament amb VSCode
              - href: ./labs/01-introduction/lab03.qmd
                text: Laboratori 3 · Hola món en C a Debian
              - href: ./labs/01-introduction/lab04.qmd
                text: Laboratori 4 · Configurant Git a la màquina virtual
              - href: ./labs/01-introduction/lab05.qmd
                text: Laboratori 5 · Calculadora col·laborativa amb C
              - href: ./labs/02-c-pointers/lab01.qmd
                text: Laboratori 6 · Punters·Heap·Stack en C
          - section: Unitat 02
            contents:
              - href: ./labs/03-syscalls/lab01.qmd
                text: Laboratori 7 · Espiant el Kernel
              - href: ./labs/03-syscalls/lab02.qmd
                text: Laboratori 8 · Anàlisi de crides a sistema
              - href: ./labs/04-kernel/lab01.qmd
                text: Laboratori 9 · Programació de mòduls per al Kernel de Linux
              - href: ./labs/04-kernel/lab02.qmd
                text: Laboratori 10 · Escalada de privilegis
          - section: Unitat 03
            contents:
              - href: ./labs/05-procs/lab01.qmd
                text: Laboratori 11 · OhMySudo!
              - href: ./labs/05-procs/lab02.qmd
                text: Laboratori 12 · Escape Room amb processos i pipes
          - section: Unitat 04
            contents:
              - href: ./labs/06-sched/01-simulador.qmd
                text: Laboratori 13 · Simulador d'algorismes de planificació de processos
              
      - section: Projectes
        contents:
          - href: ./projects/project01.qmd
            text: Pràctica 01 · Manipulació de Cadenes de Caràcters en C
          - href: ./projects/project02.qmd
            text: Pràctica 02 · Implementació d'una Shell en C
      - section: Activitats
        contents:
          - section: Unitat 01
            contents:
              - href: ./activities/unit00/01-debianbin.qmd
                text: RMSF · Implementant una paperera de reciclatge a Linux
              - href: ./activities/unit00/02-ex01-c.qmd
                text: Exercicis amb C - Pokemon· 
              - href: ./activities/unit00/03-ex02-c.qmd
                text: Exercicis amb C
          - section: Unitat 02
            contents:
              - href: ./activities/unit01/01-kernel.qmd
                text: Compilant el Kernel de Linux
          - section: Unitat 03
            contents:
              - href: ./activities/unit02/01-create.qmd
                text: Exercici · Creació de processos
              - href: ./activities/unit02/02-pipes.qmd
                text: Exercici · Pipes i redireccions
          - section: Unitat 04
            contents:
              - href: ./activities/unit03/01-sched.qmd
                text: Exercici · Planificació de processos
              


  
format:
  html:
    toc: true
    theme: 
      - cosmo
      - brand

